version: "3.9"

services:
  proxy:
    image: nginx:alpine
    container_name: piyomiru-proxy
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - web
      - api

  socket:
    image: node:16-alpine
    container_name: piyomiru-socket
    working_dir: /app
    volumes:
      - ./socket:/app
    ports:
      - 3001:3001
    command: >
      sh -c "
        npm install -g nodemon &&
        npm install &&
        nodemon app
      "

  web:
    image: node:16-alpine
    container_name: piyomiru-web
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - 3000:3000
    command: >
      sh -c "
        npm install &&
        npm run start
      "

  api:
    image: node:16-alpine
    container_name: piyomiru-api
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - 1337:1337
    command: >
      sh -c "
        yarn &&
        yarn develop
      "