version: "3.9"

services:
  web:
    image: node:lts-alpine
    container_name: piyomiru-web
    working_dir: /app
    volumes:
      - ../web:/app
    ports:
      - 3000:3000
    command: >
      sh -c "
        npm install &&
        npm run start
      "

  api:
    image: node:lts-alpine
    container_name: piyomiru-api
    working_dir: /app
    volumes:
      - ../api:/app
    ports:
      - 1337:1337
    command: >
      sh -c "
        yarn &&
        yarn develop
      "